/* Generated by scripts/generate-seo-pages.py — do not edit by hand. */
window.LUMA_SEO = {
  "siteUrl": "https://lumasmarthome.com",
  "routes": {
    "home": {
      "id": "home",
      "path": "/",
      "title": "LUMA Smart Home | Lighting, Shades & AV in Sarasota, FL",
      "description": "LUMA designs and installs lighting control, motorized shades, security, audio, and Wi-Fi for fine homes on Florida's Gulf Coast. Serving Sarasota, Manatee, Charlotte, Lee & Collier Counties."
    },
    "lighting": {
      "id": "lighting",
      "path": "/lighting",
      "title": "Smart Lighting Control | Lutron & Ketra | LUMA Smart Home",
      "description": "Decorative and architectural lighting under one control spec. Lutron RadioRA 3, Ketra, warm-dim scenes, and designer keypads for Gulf Coast homes."
    },
    "shading": {
      "id": "shading",
      "path": "/shading",
      "title": "Motorized Window Shades | Somfy & Lutron Sivoia | LUMA",
      "description": "Motorized shades and drapery for Gulf Coast sun: solar screens, blackout, and Lutron Sivoia QS / Somfy, programmed to the hour of the day."
    },
    "theaters": {
      "id": "theaters",
      "path": "/theaters",
      "title": "Home Theater Design & Installation | Sarasota | LUMA",
      "description": "Dedicated cinema rooms designed from the walls out — acoustics, sightlines, calibration, and seating for Gulf Coast residences."
    },
    "automation": {
      "id": "automation",
      "path": "/automation",
      "title": "Home Automation | Control4, Lutron, Josh.ai | LUMA Sarasota",
      "description": "One-press scenes that move lighting, shades, climate, audio, and security together. Open platforms — Control4, Lutron, Josh.ai — for Gulf Coast homes."
    },
    "audio": {
      "id": "audio",
      "path": "/audio",
      "title": "Whole-Home Audio & Video | Sonos, Sonance | LUMA Smart Home",
      "description": "Invisible in-ceiling, in-wall, and outdoor audio tuned to each room, with one app across every zone. Sarasota to Naples."
    },
    "security": {
      "id": "security",
      "path": "/security",
      "title": "Home Security & Cameras | UniFi Protect | LUMA Sarasota",
      "description": "On-premise UniFi Protect cameras with no monthly cloud fees. Property-walked camera placement, NVR on site, optional alarm monitoring."
    },
    "networking": {
      "id": "networking",
      "path": "/networking",
      "title": "Wi-Fi 6/7 & Structured Cabling | UniFi | LUMA Smart Home",
      "description": "Enterprise-grade UniFi Wi-Fi and Cat6A structured cabling designed before drywall. Wired spine first, wireless where it belongs."
    },
    "designers": {
      "id": "designers",
      "path": "/designers",
      "title": "For Designers & Builders | Trade Partner | LUMA Smart Home",
      "description": "One low-voltage trade for lighting, shades, AV, security, and networking. Trade pricing, submittal packages, and site coordination for ASID, AIA, and GCs on the Gulf Coast."
    },
    "work": {
      "id": "work",
      "path": "/work",
      "title": "Our Work & Testimonials | Gulf Coast Homes | LUMA",
      "description": "Selected residences and five-star reviews from homeowners, architects, and builders along Florida's Gulf Coast."
    },
    "about": {
      "id": "about",
      "path": "/about",
      "title": "About LUMA Smart Home | Sarasota Residential Technology Studio",
      "description": "LUMA is a Sarasota residential technology studio. Open platforms, line-item proposals, and ongoing care from Bradenton to Naples."
    },
    "contact": {
      "id": "contact",
      "path": "/contact",
      "title": "Start a Project | Contact LUMA Smart Home | Sarasota, FL",
      "description": "Book a consultation with LUMA Smart Home. Serving Sarasota, Manatee, Charlotte, Lee, and Collier Counties. Call +1 (941) 217-1616."
    },
    "budget-calculator": {
      "id": "budget-calculator",
      "path": "/budget",
      "title": "Smart Home Budget Calculator | Gulf Coast Ranges | LUMA",
      "description": "Honest budget ranges for Gulf Coast smart homes — lighting, shades, audio, theater, security, and networking. Walk through it like we would on site."
    },
    "support": {
      "id": "support",
      "path": "/support",
      "title": "LUMA Care | Smart Home Support Plans | Sarasota, FL",
      "description": "Ongoing stewardship for the systems we installed — remote diagnostics, scene tweaks, and technicians who already know your rack. LUMA Care memberships."
    },
    "smart-home-demo": {
      "id": "smart-home-demo",
      "path": "/demo",
      "title": "Interactive 3D Smart Home Demo | LUMA Smart Home",
      "description": "Explore a cutaway Gulf Coast home and see lighting, shades, audio, security, and networking in place — with packages and pricing."
    },
    "case-spacious": {
      "id": "case-spacious",
      "path": "/work/spacious-modern",
      "title": "Spacious Modern | Naples Port Royal Case Study | LUMA",
      "description": "A 7,400 sq ft Naples home with Sonos whole-home audio, UniFi networking, and WattBox managed power — calm in the rooms, organized in the rack."
    },
    "case-urban": {
      "id": "case-urban",
      "path": "/work/urban-home",
      "title": "Urban Home | Sarasota Bird Key Case Study | LUMA",
      "description": "A Bird Key waterfront residence built around Bowers & Wilkins, a 7.1.2 Atmos array, landscape audio, and a UniFi network."
    },
    "case-family": {
      "id": "case-family",
      "path": "/work/huge-family-house",
      "title": "Huge Family House | Bonita Bay Lighting Case Study | LUMA",
      "description": "A 9,000+ sq ft Bonita Bay residence with hidden cove LEDs, layered Lutron RadioRA 3 scenes, and designer keypads in every room."
    },
    "case-modern": {
      "id": "case-modern",
      "path": "/work/modern-residence",
      "title": "Modern Residence | Tampa Bay AV Case Study | LUMA",
      "description": "Five independent AV zones in a hillside home — entertainment room, living room, and three outdoor patios — unified under one control layer."
    },
    "case-bighouse": {
      "id": "case-bighouse",
      "path": "/work/big-modern-house",
      "title": "Big Modern House | Whole-Home Integration Case Study | LUMA",
      "description": "16 audio zones, 6 video zones, a Dolby Atmos theater, and 80+ speakers from a single processor — documented for long-term ownership."
    }
  }
};
window.LUMA_SEO_ALIASES = {"budget": "budget-calculator", "projects": "work", "our-work": "work", "serviceplans": "support", "service-plans": "support", "customer-support": "support", "smart-home-demo": "smart-home-demo", "builders": "designers"};
